[Enhancement]: use enum for defining valid actions
kalviumcommunity/whosin pull request #8
Opened 2023-11-10 17:29 UTC by ishan21sh

## Summary of the pull request

### New

-   Added Action enum in manual mode

## Detailed description of the pull request / Additional comments
This adds _enum.ts for manual mode. The enum is used to define the valid actions and use it at the places where hardcoded string were being used earlier. I think this should close the mentioned issue. Looking forward to getting some reviews on this one. 
Thanks in advance.

## PR checklist
- [x] Closes #7
- [x] Feature or Enhancement
- [ ] Documentation updated

2023-11-11 04:23 UTC, th3c0d3br34ker commented on src/modes/manual.mode/_enum.ts
> +export { Action };
Please make it as a `default` export.

2023-11-11 04:25 UTC, th3c0d3br34ker requested changes
Please resolve the added comments.

2023-11-11 04:52 UTC, th3c0d3br34ker commented
thanks @ishan21sh on your submission. common feedback -- please comment first on the issue that you wish to work on, before you are starting on it. this helps any other contributor understand that you have picked up the issue.

2023-11-13 04:36 UTC, ishan21sh commented
Yeah I will make the required changes thank you for the feedback and sorry for the delay was busy with some other assignments

2023-11-13 07:02 UTC, th3c0d3br34ker commented
hey @ishan21sh please update the usage of the `Action` in [manual.ts](https://github.com/kalviumcommunity/whosin/pull/8/files#diff-9bedced141656d2bb80befb5be8c59f143c2fee09c4c0ad95ab70d6976a947a8) as well.

2023-11-13 07:10 UTC, th3c0d3br34ker requested changes
Please resolve the added comments.

2023-11-13 15:10 UTC, ishan21sh commented
Made the required Improvements
1. Changed he variable name 'ACTION' to 'ACTIONS'
2. Added formatting using npm run format

2023-11-14 04:21 UTC, th3c0d3br34ker requested changes
hey @ishan21sh, suggestion -- 
1. the variable `ACTIONS` is expected to be capitalized.
2. please don't commit changes to files where you haven't made any changes like `package-lock.json` and `requestLogger.ts`

2023-11-14 06:51 UTC, th3c0d3br34ker requested changes

2023-11-14 06:51 UTC, th3c0d3br34ker commented on package-lock.json
please reset this file.

2023-11-14 06:51 UTC, th3c0d3br34ker commented on src/middlewares/requestLogger.ts
please reset this file.

2023-11-14 10:52 UTC, th3c0d3br34ker approved these changes
thanks @ishan21sh for your support. this PR looks good to be merged. ✨

2023-11-14 11:56 UTC, ishan21sh commented
Thank you sir for the feedbacks and opportunity

2023-11-14 13:08 UTC, merged